import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createExecutionBudget } from '../netlify/functions/_shared/runtime.mjs';
import { MEMORY_POLICY, selectMemoryContext, formatMemoryContext } from '../netlify/functions/_shared/memory.mjs';
const now=Date.now(),memories=[];for(let i=0;i<45;i++)memories.push({id:`m${i}`,type:'manual_note',content:`manual ${i}`,confidence:100,created_at:new Date(now-i*1000).toISOString()});
memories.push({id:'explicit-old',type:'explicit_instruction',content:'Never change the project identity.',confidence:100,created_at:new Date(now-9999999).toISOString()});
const selection=selectMemoryContext(memories);assert.ok(selection.selected.length<=MEMORY_POLICY.maxItems);assert.ok(selection.chars<=MEMORY_POLICY.maxChars);assert.ok(selection.selected.some(m=>m.id==='explicit-old'));assert.ok(formatMemoryContext(selection).includes('ranked by type priority, confidence, then recency'));
const reserveBudget=createExecutionBudget({startedAt:Date.now(),timeoutMs:10000,maxCalls:5,reserveMs:1000});assert.equal(reserveBudget.canCall(1200,9000),false);assert.throws(()=>reserveBudget.reserveCall('review',9000),e=>e?.code==='EXECUTION_BUDGET_EXHAUSTED');
const modelsSource=readFileSync('netlify/functions/_shared/models.mjs','utf8'),chatSource=readFileSync('netlify/functions/chat.mjs','utf8');
assert.ok(modelsSource.includes("strategy:verify?'author_adversary_patch':'single_author'"));assert.ok(!modelsSource.includes('bounded specialist assisting Zeus'));assert.ok(modelsSource.includes("strategy:'scoped_specialists_director_adversary_patch'"));assert.ok(modelsSource.includes('maxAttempts:5'));assert.ok(chatSource.includes('verificationLabel:result.verificationLabel||null'));
globalThis.Netlify={env:{get(name){return ({OPENAI_API_KEY:'openai-test',OPENAI_BASE_URL:'https://openai.test/v1',ANTHROPIC_API_KEY:'anthropic-test',ANTHROPIC_BASE_URL:'https://anthropic.test'})[name]||'';}}};
const originalFetch=globalThis.fetch;let providerCalls=0;
globalThis.fetch=async(url,options={})=>{providerCalls++;if(String(url).includes('anthropic.test')){const body=JSON.parse(String(options.body||'{}')),system=String(body.system||'');if(system.includes('original author applying one bounded repair pass'))return new Response(JSON.stringify({content:[{type:'text',text:'FIXED ANSWER with validateToken() and error handling.'}]}),{status:200,headers:{'content-type':'application/json'}});return new Response(JSON.stringify({content:[{type:'text',text:'DRAFT ANSWER calls validateToken() without an error path.'}]}),{status:200,headers:{'content-type':'application/json'}});}const body=JSON.parse(String(options.body||'{}')),system=String(body.messages?.[0]?.content||'');if(system.includes('adversarial QA reviewer')){const findings=[{kind:'empty_error_path',requirement_id:'R1',location:'validateToken',evidence:'validateToken() without an error path',defect:'The quoted call has no error path even though the request requires safe auth handling.',suggested_fix:'Add a bounded error path.'}];return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(findings)}}]}),{status:200,headers:{'content-type':'application/json'}});}return new Response(JSON.stringify({choices:[{message:{content:'fallback'}}]}),{status:200,headers:{'content-type':'application/json'}});};
try{const models=await import(`../netlify/functions/_shared/models.mjs?finalfix2=${Date.now()}`);const result=await models.runZeus({text:'Implement secure authentication and make sure errors are handled.',verify:true,requirements:{items:[{id:'R1',text:'Make sure authentication errors are handled.',evidence:'make sure errors are handled',central:true}],ambiguous:false}});assert.equal(result.content,'FIXED ANSWER with validateToken() and error handling.');assert.equal(result.trace.strategy,'author_adversary_patch');assert.equal(result.trace.acceptedFindings.length,1);assert.equal(result.trace.verification,'patched_once');assert.equal(providerCalls,3);}finally{globalThis.fetch=originalFetch;delete globalThis.Netlify;}
console.log('Final Fix 2/3 reliability engine tests: PASS');
