import JSZip from 'jszip';
import ExcelJS from 'exceljs';
import { isSensitiveFilename, safeExtractedText } from './security.mjs';
import { assertSafeZip, verifyZipEntries } from './archive-safety.mjs';

const decode=(buf)=>new TextDecoder('utf-8',{fatal:false}).decode(buf);
const stripXml=(s)=>s.replace(/<w:tab\/?\s*>/g,'\t').replace(/<w:br\/?\s*>/g,'\n').replace(/<a:br\/?\s*>/g,'\n').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
function result(text='',status='stored_only',{reason=null,truncated=false}={}){return {text:String(text||''),status,reason,truncated:Boolean(truncated),extractable:status==='analyzable'};}
function safeResult(raw,filename,max=120000,extra={}){const source=String(raw||''),sanitized=safeExtractedText(source,filename),clipped=sanitized.slice(0,max);return result(clipped,clipped.trim()?'analyzable':'empty',{...extra,truncated:Boolean(extra.truncated||sanitized.length>max)});}
export async function extractFile(buffer,mime='',filename=''){
  const lower=(filename||'').toLowerCase();
  if(isSensitiveFilename(lower))return result('[Sensitive configuration/credential file omitted from AI context.]','omitted_sensitive',{reason:'sensitive_filename'});
  try{
    if(mime.startsWith('text/')||/\.(txt|md|csv|json|xml|log|ini|cfg)$/i.test(lower))return safeResult(decode(buffer),filename);
    if(mime==='application/pdf'||lower.endsWith('.pdf')){const mod=await import('pdf-parse'),parse=mod.default||mod,out=await parse(Buffer.from(buffer));return safeResult(out.text||'',filename);}
    if(lower.endsWith('.docx')||mime.includes('wordprocessingml')){const inspection=assertSafeZip(buffer,'office');verifyZipEntries(buffer,inspection,{names:['word/document.xml'],maxEntryOutput:12*1024*1024,maxTotalOutput:12*1024*1024});const zip=await JSZip.loadAsync(buffer),xml=await zip.file('word/document.xml')?.async('string');return safeResult(xml?stripXml(xml):'',filename);}
    if(lower.endsWith('.pptx')||mime.includes('presentationml')){const inspection=assertSafeZip(buffer,'office'),allSlides=inspection.manifest.map(x=>x.name).filter(k=>/^ppt\/slides\/slide\d+\.xml$/.test(k)).sort(),slideNames=allSlides.slice(0,100);verifyZipEntries(buffer,inspection,{names:slideNames,maxEntryOutput:2*1024*1024,maxTotalOutput:16*1024*1024});const zip=await JSZip.loadAsync(buffer),texts=[];for(const k of slideNames){const file=zip.file(k);if(file)texts.push(stripXml(await file.async('string')));}return safeResult(texts.join('\n\n'),filename,120000,{truncated:allSlides.length>slideNames.length});}
    if(lower.endsWith('.zip')||mime==='application/zip'||mime==='application/x-zip-compressed'){const inspection=assertSafeZip(buffer,'generic'),zip=await JSZip.loadAsync(buffer),textExt=/\.(?:txt|md|json|js|mjs|cjs|ts|tsx|jsx|css|scss|html|htm|xml|yml|yaml|toml|sql|py|java|go|rs|sh|ini|cfg|csv)$/i,eligible=inspection.manifest.map(x=>x.name).filter(Boolean).filter(name=>zip.files[name]&&!zip.files[name].dir&&textExt.test(name)&&!isSensitiveFilename(name)&&!/(^|\/)(node_modules|\.git|dist|build|coverage|\.next)(\/|$)/i.test(name)),names=eligible.slice(0,90);verifyZipEntries(buffer,inspection,{names,maxEntryOutput:350000,maxTotalOutput:12*1024*1024});const chunks=[];let total=0,truncated=eligible.length>names.length;for(const name of names){if(total>=115000){truncated=true;break;}const entry=zip.file(name);if(!entry)continue;const raw=await entry.async('uint8array');if(raw.byteLength>350000){truncated=true;continue;}const text=safeExtractedText(decode(raw).replace(/\0/g,''),name).slice(0,18000);if(!text.trim())continue;const chunk=`FILE: ${name}\n${text}`;chunks.push(chunk);total+=chunk.length;}const omittedSensitive=Object.keys(zip.files).some(name=>!zip.files[name].dir&&isSensitiveFilename(name));if(omittedSensitive)chunks.unshift('[Sensitive credential/configuration files were omitted from AI context.]');return safeResult(chunks.join('\n\n---\n\n'),filename,120000,{truncated});}
    if(lower.endsWith('.xlsx')||mime.includes('spreadsheetml')){const inspection=assertSafeZip(buffer,'office');verifyZipEntries(buffer,inspection,{maxEntryOutput:12*1024*1024,maxTotalOutput:48*1024*1024});const wb=new ExcelJS.Workbook();await wb.xlsx.load(Buffer.from(buffer));const out=[];let truncated=wb.worksheets.length>30;for(const ws of wb.worksheets.slice(0,30)){out.push(`SHEET: ${ws.name}`);let rows=0,totalRows=0;ws.eachRow({includeEmpty:false},row=>{totalRows+=1;if(rows>=1000){truncated=true;return;}const values=(row.values||[]).slice(1).map(v=>{if(v==null)return '';if(typeof v==='object'){if('text' in v)return String(v.text||'');if('result' in v)return String(v.result??'');if('richText' in v)return (v.richText||[]).map(x=>x.text||'').join('');}return String(v);});out.push(values.map(v=>/[",\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v).join(','));rows+=1;});if(totalRows>rows)truncated=true;if(out.join('\n').length>110000){truncated=true;break;}}return safeResult(out.join('\n'),filename,120000,{truncated});}
    if(lower.endsWith('.xls'))return result('[Legacy .xls extraction is not supported. Convert the spreadsheet to .xlsx or .csv for analysis.]','unsupported',{reason:'legacy_xls'});
    if(/^image\//i.test(mime))return result('','vision_only',{reason:'image_requires_vision'});
    if(/^video\//i.test(mime))return result('','stored_only',{reason:'video_requires_sampled_frames'});
    return result('','stored_only',{reason:'unsupported_file_type'});
  }catch(error){if(error?.code&&/^ARCHIVE_/.test(error.code))throw error;console.error('File extraction failed',error?.message||error);return result('','failed',{reason:'extraction_failed'});}
}
export async function extractText(buffer,mime='',filename=''){return (await extractFile(buffer,mime,filename)).text;}
