function zipOutputError(message, code='ZIP_OUTPUT_INVALID') {
  const error = new Error(message);
  error.code = code;
  error.status = 422;
  return error;
}

export function safeZipPath(raw) {
  const normalized=String(raw||'').trim().replace(/\\/g,'/');
  if(!normalized||normalized.startsWith('/')||/^[A-Za-z]:\//.test(normalized))return null;
  const rawParts=normalized.split('/').map(p=>p.trim());
  if(rawParts.some(p=>p==='..'))return null;
  const clean=rawParts
    .filter((p)=>p&&p!=='.')
    .map((p)=>p.replace(/[<>:"|?*\0]+/g,'-'))
    .slice(0,10);
  const joined=clean.join('/');
  return joined&&joined.length<=180?joined:null;
}

export function filesFromModelText(title, content, { maxFiles=60, maxFileChars=300000, maxTotalChars=1600000 }={}) {
  const text=String(content||'');
  const files=[];
  const seen=new Set();
  const re=/```(?:[\w.+-]+)?[ \t]+([^\n`]+)\n([\s\S]*?)```/g;
  let match,total=0;
  while((match=re.exec(text))){
    const path=safeZipPath(match[1].trim());
    if(!path||seen.has(path))continue;
    const data=match[2].replace(/\n$/,'');
    if(data.length>maxFileChars)throw zipOutputError(`Generated file ${path} is too large.`, 'ZIP_FILE_TOO_LARGE');
    total+=data.length;
    if(total>maxTotalChars)throw zipOutputError('Generated ZIP source exceeds the safe output budget.', 'ZIP_OUTPUT_TOO_LARGE');
    seen.add(path);files.push({path,data});
    if(files.length>=maxFiles)break;
  }
  const nonReadme=files.filter(f=>f.path.toLowerCase()!=='readme.md');
  if(!files.length||!nonReadme.length){
    throw zipOutputError('The model did not return a valid multi-file ZIP manifest. Retry the request so OlyHub can generate real files instead of an empty archive.', 'ZIP_MANIFEST_MISSING');
  }
  if(!seen.has('README.md'))files.unshift({path:'README.md',data:`# ${String(title||'OlyHub Output').trim()||'OlyHub Output'}\n\nGenerated by OlyHub. Files in this archive were validated from explicit fenced file blocks.`});
  return files;
}
